ports:
  traefik:
    hostPort: 9000
  web:
    hostPort: 80

pilot:
  enabled: true
  token: f82daf08-39a8-43df-a771-157d2e63101f

experimental:
  plugins:
    enabled: true

additionalArguments:
- --experimental.plugins.opa.moduleName=github.com/team-carepay/traefik-opa-plugin
- --experimental.plugins.opa.version=v0.0.3
